### ISSUE TITLE
Create package for pip

### ISSUE THREAD

**Issue by astagi** [Owanesh/italian-vip-says#2]
This guide is really useful http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by astagi** [comment]
This guide is really useful http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by swapsha96** [comment]
I've experience in building Python packages (e.g. [Omnicorn](https://github.com/swapsha96/omnicorn)). Please assign this to me.

**Comment by astagi** [comment]
Sure @swapsha96 thank you :)

**Comment by a-arpit94** [comment]
I want to help too.

**Comment by kalbhor** [comment]
I'd love to help too!

**Comment by Abelarm** [comment]
HAHAHAHA
complimenti per il package!

se hai qualche altra idea di funzionalità crea una issue mi piacerebbe lavorarci su!

**Comment by astagi** [comment]
it's assigned to @swapsha96 for now :) he asked to pick up the issue first.

@Abelarm thank you, I'll let you know (if you know another Italian vip that can be "coded" feel free to open a PR ;) )

**Comment by swapsha96** [comment]
@astagi The PR is merged. Can you please close this issue?

**Comment by astagi** [comment]
Sure @swapsha96 thank you for your contribution 💪
